[_]
schema-version = "0.2"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-base"
exclude = ["/README.md", ".venv", "tests/", "docs/"]

[[io.buildpacks.group]]
uri = "paketo-buildpacks/python"

[[io.buildpacks.build.env]]
name = "BP_PYTHON_VERSION"
value = "3.13"

[[io.buildpacks.build.env]]
name = "BP_UV_VERSION"
value = "0.9"
